config/routes.rb
Rails.application.routes.draw do

  
  resources :members

  resources :groups

  resources :products

  resources :subcats

  resources :cats

  resources :sub_categories

  resources :categories

  resources :news

  resources :documents

  resources :manage # users and admins

  devise_for :users

  devise_for :admins
  
  root to: "news#index"

  get 'news_search' => 'news#search'

  get 'documents/cat/:id' => 'documents#by_category'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
   # console.log(user.to_yaml)
     user ||= User.new # guest user (not logged in)
     #   if user.admin?
     #    can :manage, :all
    #   else
         can :read, :all
      # end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/authorize.rb
class Authorize < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :document
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :documents, :through => :categorizations
  has_many :visibilities
  has_many :groups, :through => :visibilities

  def self.newest
       cat_list = {}
       cat_query = " select distinct
                      public.documents.id as document_id, 
                      public.categories.id as category_id,
                      public.categories.name as category_name,
                      public.categories.parent_id
                      FROM  public.documents 
                      INNER JOIN public.categorizations ON public.documents.id = public.categorizations.document_id
                      INNER JOIN public.categories ON public.categories.id = public.categorizations.category_id
                      INNER JOIN public.visibilities ON public.categories.id = public.visibilities.category_id
                      INNER JOIN public.groups ON public.groups.id = public.visibilities.group_id"                 
      @categories = Document.all.find_by_sql(cat_query) 
      cathash = []
      @categories.each do |category| 
        if  cathash["#{category.category_name}"] 
            cathash["#{category.category_name}"]  = cathash["#{category.category_name}"]  +  1
        else
            cathash["#{category.category_name}"]  = 1
        end
      end
    cathash
  end


end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :categorizations
  has_many :categories, :through => :categorizations
  has_attached_file :file_name

 # validates_attachment_presence :file_name
  validates_attachment_content_type :file_name, :content_type => 
    ['image/jpg',
    'image/jpeg',
    'image/pjpeg',
    'image/png',
    'image/x-png',
    'image/gif',
    'application/pdf',
    'application/msword',
    'applicationvnd.ms-word',
    'applicaiton/vnd.openxmlformats-officedocument.wordprocessingm1.document',
    'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain']
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :authorizes
  has_many :users, :through => :authorizes
  has_many :visibilities
  has_many :categories, :through => :visibilities
end

app/models/member.rb
class Member < ActiveRecord::Base
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authorizes
  has_many :groups, :through => :authorizes
         
end

app/models/visibility.rb
class Visibility < ActiveRecord::Base
   belongs_to :group
    belongs_to :category
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index, :show, :search]
  # GET /news
  # GET /news.json
  def index
    if params['search_term']
      @news = News.where("LOWER(title) LIKE :title OR LOWER(content) LIKE :content OR LOWER(tags) LIKE :content",{:title => "%#{params['search_term'].downcase}%",:content=>"%#{params['search_term'].downcase}%"})
    else
      @news = News.all
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end


  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_url, notice: 'News was successfully created.' }
        format.json { render action: 'show', status: :created, location: @news }
      else
        format.html { render action: 'new' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to news_index_url, notice: 'News was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :content, :updated, :tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/subcats_helper.rb
module SubcatsHelper
end

app/views/news/_form.html.erb
<%= simple_form_for(@news) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
  <%= f.input :title, label: 'Title' %>
  <%= f.input :tags, label: 'Tags',hint: 'Single words seperated by spaces only' %>
  <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  <%= f.input :updated %>
  </div>
  <div class="form-submit">
    <%= f.button :submit , :class => "btn btn-success"%>
  </div>
<% end %>
<%= tinymce %>

app/views/news/edit.html.erb
<h1>Edit News</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path, :class => "btn btn-warning" %>

app/views/news/index.html copy 2.erb
<h1>News</h1>
<table class="table table-striped table-bordered table-hover" width="744"> 
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.content %></td>
        <td><%= news.updated %></td>
        <td><%= link_to 'Show', news, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_news_path(news) , :class => "btn btn-info" %></td>
        <td><%= link_to 'Delete', news, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New News', new_news_path, :class => "btn btn-success"  %>
<br><br>

app/views/news/index.html copy.erb
<h1>News</h1>
<table class="table table-striped table-bordered table-hover" width="744"> 
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Updated</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.Title %></td>
        <td><%= news.Content %></td>
        <td><%= news.Updated %></td>
        <td><%= link_to 'Show', news, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_news_path(news) , :class => "btn btn-info" %></td>
        <td><%= link_to 'Delete', news, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New News', new_news_path, :class => "btn btn-success"  %>
<br><br>

app/views/news/index.html.erb
<h3>Welcome to the ELI Client Portal</h3>
<h5>Recent News</h5>


<table width="100%" border="0">
   <% @news.each do |article| %>    
    <tr>
    <td><span class='news-title'><%= article.title %></span></td>
  </tr>
    <tr>
    <td><span class='news_date'><%= article.updated_at.strftime('%B %e at %l:%M %p') %></span></td>
  </tr> 
 
  <tr>
    <td><%= article.content.html_safe %></td>
  </tr>
 <tr>
    <td><%= link_to 'Read More', article %></td>
  </tr>
<% if user_signed_in? %>
<% if  current_user.has_role? :admin %>
<tr>
<td><%= link_to 'Edit', edit_news_path(article) , :class => "btn btn-info" %>&nbsp;<%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
</td>
</tr>
<% end %>
<% end %>
  <tr class='news-seperator'>
    <td>&nbsp;</td>
  </tr>
  <% end %>
</table>
<br>
<% if user_signed_in? %>
  <% if  current_user.has_role? :admin %>
<%= link_to 'Add News', new_news_path, :class => "btn btn-success"  %>
  <% end %>
<% end %>

app/views/news/new.html.erb
<h1>Add A News Article</h1>

<%= render 'form' %>

<%= link_to 'Back', news_index_path , :class => "btn btn-warning" %>

app/views/news/search.html.erb
here are your search results

app/views/news/show.html.erb
<div class='news-title'><%= @news.title %></div>
<div class='news-content'><%= @news.content.html_safe %></div>
<div class='news-updated'><%= @news.updated %></div>

<%= link_to 'Edit', edit_news_path(@news) , :class => "btn btn-edit"%> |
<%= link_to 'Back', news_index_path, :class => "btn btn-back" %>