config/routes.rb
Rails.application.routes.draw do

  
  resources :members

  resources :groups

  resources :products

  resources :subcats

  resources :cats

  resources :sub_categories

  resources :categories

  resources :news

  resources :documents

  resources :manage # users and admins

  devise_for :users

  devise_for :admins
  
  root to: "news#index"

  get 'news_search' => 'news#search'

  get 'documents/cat/:id' => 'documents#by_category'

end

app/models/document.rb
class Document < ActiveRecord::Base
  has_many :categorizations
  has_many :categories, :through => :categorizations
  has_attached_file :file_name

 # validates_attachment_presence :file_name
  validates_attachment_content_type :file_name, :content_type => 
    ['image/jpg',
    'image/jpeg',
    'image/pjpeg',
    'image/png',
    'image/x-png',
    'image/gif',
    'application/pdf',
    'application/msword',
    'applicationvnd.ms-word',
    'applicaiton/vnd.openxmlformats-officedocument.wordprocessingm1.document',
    'application/msexcel','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/mspowerpoint','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'text/plain']
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
 # before_action :authenticate_user!, :except => [:index]
  before_action :authenticate_user!
  # GET /documents
  # GET /documents.json
  def index
  #  if current_user.id == 6
  #    base_query = "SELECT public.documents.* from  public.documents" 
  #  else
      base_query = "SELECT distinct public.documents.*
        FROM public.documents INNER JOIN public.categorizations ON public.documents.id = public.categorizations.document_id
          INNER JOIN public.categories ON public.categories.id = public.categorizations.category_id
          INNER JOIN public.visibilities ON public.categories.id = public.visibilities.category_id
          INNER JOIN public.groups ON public.groups.id = public.visibilities.group_id 
          where
          public.groups.id in (select distinct public.authorizes.group_id from public.authorizes where authorizes.user_id = #{current_user.id})"
   # end

    restrictors =[]
    if params['search_term']
      terms = params['search_term'].downcase.split
      terms.each{ |term| restrictors << "LOWER(title) LIKE '%#{term}%' OR LOWER(content) LIKE '%#{term}%' OR LOWER(tags) LIKE '%#{term}%'" }
    end
    
    restrictions = ''
    restrictors.each_with_index{ |restriction, i| 
     if i == 0 
       restrictions = " and #{restriction}"
     else 
        restrictions = " #{restrictions} or #{restriction}"
      end   
    }
Rails.logger.debug "\n\n\n**** base query: #{base_query} ****\n\n\n"
Rails.logger.debug "\n\n\n**** restrictions: #{restrictions} ****\n\n\n"
    @documents = Document.all.find_by_sql("#{base_query}#{restrictions}") 

### categories

   

  end

  # GET /documents/cat/1
  def by_category
    if params['id']
      @documents  = Document.joins(:categories).select("documents.*,categories.name").where("categories.id" => params['id'])   
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_url, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to documents_url, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :vlink, :content, :tags, :status, :file_name, :category_ids => [])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= simple_form_for @document do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, label: 'Title' %>
  <%= f.input :tags, label: 'Tags', hint: 'Single words seperated by spaces only' %>
  <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  
<div class="category-container">  
<%= f.association :categories, as: :check_boxes,  collection: Category.order('sort_id ASC'), :include_blank => false, :class => "category-labels", :label_method => lambda { |cat|

if cat.parent_id == 0 
  "<span class='category-primary'>#{cat.name}</span>".html_safe 
else
  "<span class='category-secondary'>#{cat.name}</span>".html_safe 
end }%>
</div>
<%= f.input :vlink, label: 'vLink', hint: 'Leave blank if adding files.' %>

<div class="file-container">
  <%= f.file_field :file_name %>
</div>
  <%= f.button :submit , :class => "btn btn-success" %>
<% end %>
<%= tinymce %>

app/views/documents/by_category.html.erb
<h3>By Category <%= @documents.first.name %></h3>

<table width="100%" border="0" cellpadding='5'>
  <% @documents.each do |document| 
      @mine = Document.find(document.id)
  %>     
  <tr>
    <td rowspan="3" width='200'>
      <% if document.vlink.blank? %>


      <% if document.file_name_content_type == 'application/pdf' %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/adobe_icon.png", 
            :border=>0, :size => "200") %>
       <% elsif document.file_name_content_type == 'application/msword' %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/word_icon.png", 
            :border=>0, :size => "200") %>
       <% elsif document.file_name_content_type == 'application/msexcel' ||'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/excel_icon.png", 
            :border=>0, :size => "200") %>            
      <% else %>
        <%= image_tag(@mine.file_name.url(),:size => "200" ) %>      
      <% end %> 
      <% else %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/video.jpg", :border=>0, :size => "200") %>

      <% end %>


    </td>
    <td><h3><%= document.title %></h3></td>
  </tr>


<% if !document.vlink.blank? %>
   <tr>
    <td><%= raw(document.vlink) %>
    </td>
  </tr><tr>
    <td><%= document.content.html_safe %></td>
  </tr>
<% else %>
  <tr>
    <td><%= document.content.html_safe %></td>
  </tr>
  <tr>
    <td><%= link_to "Download Document", document.file_name.url(:original, false) %></td>
  </tr>
<% end %>
  <% if user_signed_in? %>
  <% if  current_user.has_role? :admin %>
  <tr>
    <td><%= link_to 'Edit', edit_document_path(document) , :class => "btn btn-info" %>&nbsp;<%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
    </td>
  </tr>
  <% end %>
  <% end %>
  <tr>
    <td colspan='3'>&nbsp;</td>
  </tr>
  <% end %>
</table>
<br>
<% if user_signed_in? %>
  <%= link_to 'New Document', new_document_path, :class => "btn btn-success"  %>
<% end %>

app/views/documents/edit.html.erb
<h1>Edit Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path, :class => "btn btn-warning" %>

app/views/documents/index.html.erb
<h3>Documents</h3>

<table width="100%" border="0" cellpadding='5'>
  <% @documents.each do |document| 
      @mine = Document.find(document.id)
  %>     
  <tr>
    <td rowspan="3" width='200'>
      <% if document.vlink.blank? %>


      <% if document.file_name_content_type == 'application/pdf' %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/adobe_icon.png", 
            :border=>0, :size => "200") %>
       <% elsif document.file_name_content_type == 'application/msword' %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/word_icon.png", 
            :border=>0, :size => "200") %>
       <% elsif document.file_name_content_type == 'application/msexcel' ||'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/excel_icon.png", 
            :border=>0, :size => "200") %>            
      <% else %>
        <%= image_tag(@mine.file_name.url(),:size => "200" ) %>      
      <% end %> 
      <% else %>
        <%= image_tag("https://s3.amazonaws.com/ws_eli/video.jpg", :border=>0, :size => "200") %>

      <% end %>


    </td>
    <td><h3><%= document.title %></h3></td>
  </tr>


<% if !document.vlink.blank? %>
   <tr>
    <td><%= raw(document.vlink) %>
    </td>
  </tr><tr>
    <td><%= document.content.html_safe %></td>
  </tr>
<% else %>
  <tr>
    <td><%= document.content.html_safe %></td>
  </tr>
  <tr>
    <td><%= link_to "Download Document", document.file_name.url(:original, false) %></td>
  </tr>
<% end %>
  <% if user_signed_in? %>
  <% if  current_user.has_role? :admin %>
  <tr>
    <td><%= link_to 'Edit', edit_document_path(document) , :class => "btn btn-info" %>&nbsp;<%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } , :class => "btn btn-danger" %>
    </td>
  </tr>
  <% end %>
  <% end %>
  <tr>
    <td colspan='3'>&nbsp;</td>
  </tr>
  <% end %>
</table>
<br>
<% if user_signed_in? %>
<% if  current_user.has_role? :admin %>
  <%= link_to 'Add Document', new_document_path, :class => "btn btn-success"  %>
<% end %>
<% end %>

app/views/documents/new.html.erb
<h1>Add New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path , :class => "btn btn-warning" %>

app/views/documents/show.html.erb
<div class='show-document-title'><%= @document.title %></div>

<div class='show-document-content'><%= @document.content.html_safe %></div>

<div class='show-document-image'><%= image_tag @document.file_name.url() %></div>

<%= link_to 'Edit', edit_document_path(@document), :class => "btn btn-edit"  %> |
<%= link_to 'Back', documents_path, :class => "btn btn-back"  %>